export const dummyUsers = [
  { id: 1, username: "user1", name: "John Doe", email: "john@example.com" },
  { id: 2, username: "user2", name: "Jane Doe", email: "jane@example.com" },
  {
    id: 3,
    username: "user1",
    name: "John Doe",
    email: "john.doe@example.com",
    active_last_24_hours: true,
  },
  {
    id: 4,
    username: "user2",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    active_last_24_hours: true,
  },
  {
    id: 5,
    username: "user3",
    name: "Michael Johnson",
    email: "michael.johnson@example.com",
    active_last_24_hours: false,
  },
  {
    id: 6,
    username: "user4",
    name: "Emily Brown",
    email: "emily.brown@example.com",
    active_last_24_hours: true,
  },
  {
    id: 7,
    username: "user5",
    name: "William Wilson",
    email: "william.wilson@example.com",
    active_last_24_hours: true,
  },
  {
    id: 8,
    username: "user6",
    name: "Sophia Lee",
    email: "sophia.lee@example.com",
    active_last_24_hours: false,
  },
  {
    id: 9,
    username: "user7",
    name: "James Martinez",
    email: "james.martinez@example.com",
    active_last_24_hours: false,
  },
  {
    id: 10,
    username: "user8",
    name: "Olivia Garcia",
    email: "olivia.garcia@example.com",
    active_last_24_hours: true,
  },
  {
    id: 11,
    username: "user9",
    name: "Daniel Robinson",
    email: "daniel.robinson@example.com",
    active_last_24_hours: true,
  },
  {
    id: 12,
    username: "user10",
    name: "Emma Taylor",
    email: "emma.taylor@example.com",
    active_last_24_hours: false,
  },
  {
    id: 13,
    username: "user11",
    name: "Alexander Clark",
    email: "alexander.clark@example.com",
    active_last_24_hours: false,
  },
  /* {
    user_id: 12,
    username: "user12",
    name: "Mia Lewis",
    email: "mia.lewis@example.com",
    active_last_24_hours: true,
  },
  {
    user_id: 13,
    username: "user13",
    name: "David Hall",
    email: "david.hall@example.com",
    active_last_24_hours: false,
  },
  {
    user_id: 14,
    username: "user14",
    name: "Ava Allen",
    email: "ava.allen@example.com",
    active_last_24_hours: true,
  },
  {
    user_id: 15,
    username: "user15",
    name: "Ethan Scott",
    email: "ethan.scott@example.com",
    active_last_24_hours: true,
  },
  {
    user_id: 16,
    username: "user16",
    name: "Isabella Green",
    email: "isabella.green@example.com",
    active_last_24_hours: true,
  },
  {
    user_id: 17,
    username: "user17",
    name: "Liam Adams",
    email: "liam.adams@example.com",
    active_last_24_hours: false,
  },
  {
    user_id: 18,
    username: "user18",
    name: "Chloe Baker",
    email: "chloe.baker@example.com",
    active_last_24_hours: false,
  },
  {
    user_id: 19,
    username: "user19",
    name: "Noah King",
    email: "noah.king@example.com",
    active_last_24_hours: true,
  },
  {
    user_id: 20,
    username: "user20",
    name: "Grace Wright",
    email: "grace.wright@example.com",
    active_last_24_hours: true,
  },*/
];

export const dummyPosts = [
  {
    id: 1,
    caption: "Beautiful sunset",
    mediaUrl: "https://example.com/sunset.jpg",
  },
  {
    id: 2,
    caption: "Amazing landscape",
    mediaUrl: "https://example.com/landscape.jpg",
  },
  {
    id: 1,
    caption: "Beautiful Sunset",
    mediaUrl: "https://example.com/sunset.jpg",
  },
  {
    id: 2,
    caption: "Beautiful sunset",
    mediaUrl: "https://example.com/post2.jpg",
    created_last_24_hours: false,
  },
  {
    id: 3,
    caption: "Coffee time",
    mediaUrl: "https://example.com/post3.jpg",
    created_last_24_hours: false,
  },
  {
    id: 4,
    caption: "Fun with friends",
    mediaUrl: "https://example.com/post4.jpg",
    created_last_24_hours: true,
  },
  {
    id: 5,
    caption: "Travel adventures",
    mediaUrl: "https://example.com/post5.jpg",
    created_last_24_hours: true,
  },
  {
    id: 6,
    caption: "First post",
    mediaUrl: "https://example.com/post1.jpg",
    created_last_24_hours: true,
  },
  {
    id: 7,
    caption: "Beautiful sunset",
    mediaUrl: "https://example.com/post2.jpg",
    created_last_24_hours: false,
  },
  {
    id: 8,
    caption: "Coffee time",
    mediaUrl: "https://example.com/post3.jpg",
    created_last_24_hours: false,
  },
  {
    id: 9,
    caption: "Fun with friends",
    mediaUrl: "https://example.com/post4.jpg",
    created_last_24_hours: true,
  },
  {
    id: 10,
    caption: "Travel adventures",
    mediaUrl: "https://example.com/post5.jpg",
    created_last_24_hours: true,
  },
  {
    id: 11,
    caption: "Gourmet delights",
    mediaUrl: "https://example.com/post6.jpg",
    created_last_24_hours: false,
  },
];
